# Generated by Django 5.0.6 on 2024-07-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenesProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia')),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='accesoriosxbox',
            options={'ordering': ['-created'], 'verbose_name': 'Accesorio Xbox', 'verbose_name_plural': 'Accesorios Xbox'},
        ),
    ]
