# Generated by Django 5.0.6 on 2024-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_imagenesproductos_alter_accesoriosxbox_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegosXbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Juego Xbox',
                'verbose_name_plural': 'Juegos Xbox',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='accesoriosxbox',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
    ]
