# Generated by Django 5.0.6 on 2024-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_accesoriosplaystation'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesoriosNintendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accesorio Nintendo',
                'verbose_name_plural': 'Accesorios Nintendo',
                'ordering': ['-created'],
            },
        ),
    ]
