# Generated by Django 5.0.6 on 2024-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_accesoriosnintendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoriosxbox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
