# Generated by Django 5.0.6 on 2024-08-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
